version: '3.9'
services:
  cassandra:
    image: cassandra:4.0
    ports:
      - "9042:9042"
    networks:
      - data_network
  zookeeper:
    image: bitnami/zookeeper:3.7.1
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - app_tier
  kafka:
    image: bitnami/kafka:3.1.1
    depends_on:
      - zookeeper
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
    ports:
      - "9092:9092"
    networks:
      - app_tier
networks:
  data_network:
  app_tier:
